# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, help_text='Количество товара', verbose_name='Количество товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ValueProductPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='productdetailvalue',
            name='product',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='valueproductposition',
            name='product_detail_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ProductDetailValue'),
        ),
        migrations.AddField(
            model_name='valueproductposition',
            name='product_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ProductPosition'),
        ),
    ]
