# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parentCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='parentCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес', max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='phone',
            field=models.CharField(blank=True, help_text='Телефон', max_length=15, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.IntegerField(choices=[(1, 'В обработке'), (2, 'Активный')], default=1, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productStatus',
            field=models.IntegerField(choices=[(1, 'Модерация'), (2, 'Активный')], default=1, verbose_name='Статус товара'),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='ProductStatus',
        ),
    ]
