# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование производителя', max_length=100, verbose_name='Наименование производителя')),
                ('address', models.CharField(help_text='Адрес', max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(help_text='Телефон', max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_now_add=True, help_text='Дата заказа', verbose_name='Дата заказа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Количество', verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Стоимость', max_digits=10, verbose_name='Стоимость')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Значение статуса', max_length=50, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование товара', max_length=50, verbose_name='Наименование товара')),
                ('description', models.CharField(help_text='Описание товара', max_length=50, verbose_name='Описание товара')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование характеристики', max_length=50, verbose_name='Наименование характеристики')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetailValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stringValue', models.CharField(help_text='Строковое значение характеристики', max_length=250, verbose_name='Строковое значение характеристики')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('productDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ProductDetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Значение статуса', max_length=50, verbose_name='Значение статуса')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='parentCategory',
            field=models.ManyToManyField(related_name='_category_parentCategory_+', to='store.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Наименование категории', max_length=50, verbose_name='Наименование категории'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='productStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ProductStatus'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.OrderStatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
