# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20160225_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес', max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='phone',
            field=models.CharField(blank=True, help_text='Телефон', max_length=15, null=True, verbose_name='Телефон'),
        ),
    ]
