# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20160225_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.IntegerField(choices=[(1, 'В обработке'), (2, 'Активный')], default=1, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productStatus',
            field=models.IntegerField(choices=[(1, 'Модерация'), (2, 'Активный')], default=1, verbose_name='Статус товара'),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='ProductStatus',
        ),
    ]
