# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20160225_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='/home/alexey/PycharmProjects/MatreshkaWebApp/static_content/media/%Y/%m/%d/', verbose_name='Наименование файла')),
                ('isMain', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
    ]
